library core;

{$I '..\lessrtti.inc'}


uses
  uTextual in 'uTextual.pas',
  uEvaluate in 'uEvaluate.pas',
  uDecoder in 'uDecoder.pas',
  uReferences in 'uReferences.pas',
  uCore in 'uCore.pas',
  uInputFile in 'uInputFile.pas',
  uPlugins in 'uPlugins.pas',
  uMsg in 'uMsg.pas',
  uFindLoaders in 'uFindLoaders.pas',
  uUI in 'uUI.pas',
  uLog in 'uLog.pas',
  uIO in 'uIO.pas',
  uMenu in 'uMenu.pas',
  uSections in 'uSections.pas',
  uVARegion in 'uVARegion.pas',
  uSection in 'uSection.pas',
  uDirtyFlags in 'uDirtyFlags.pas',
  uVirtualMemory in 'vm\uVirtualMemory.pas',
  uVMSearch in 'vm\uVMSearch.pas',
  uBytePattern in 'uBytePattern.pas',
  uDB in 'uDB.pas',
  uEndianness in 'uEndianness.pas',
  uStream in 'uStream.pas',
  uSection.FileMapped in 'uSection.FileMapped.pas',
  uCore.Save in 'uCore.Save.pas',
  uCore.Load in 'uCore.Load.pas',
  uDB.VA in 'uDB.VA.pas',
  uRegions in 'uRegions.pas',
  uUserData in 'uUserData.pas',
  uTypes.Lib in 'typelib\uTypes.Lib.pas',
  uTypes.Parsing in 'typelib\uTypes.Parsing.pas',
  uCore.MakeAndUndef in 'uCore.MakeAndUndef.pas',
  uRegions.TypeData in 'uRegions.TypeData.pas',
  uTypes.Mgr in 'typelib\uTypes.Mgr.pas',
  uTypes.Base in 'typelib\uTypes.Base.pas',
  uJobs in 'uJobs.pas',
  uTypes.Factory in 'typelib\uTypes.Factory.pas',
  uCore.Strings in '..\common\uCore.Strings.pas',
  uCore.Zip in 'uCore.Zip.pas',
  uCpus in 'uCpus.pas',
  uInternalDbgUtils in 'uInternalDbgUtils.pas',
  uRememberedVAs in 'uRememberedVAs.pas',
  uStream.MemoryStream in 'uStream.MemoryStream.pas',
  uStream.VAStream in 'uStream.VAStream.pas',
  uVATextLayout in 'uVATextLayout.pas',
  uTypes.Records in 'typelib\uTypes.Records.pas',
  uTypes.Arrays in 'typelib\uTypes.Arrays.pas',
  uTypes.Pointers in 'typelib\uTypes.Pointers.pas',
  uFunctions in 'uFunctions.pas',
  uSymbols.Import in 'uSymbols.Import.pas',
  uFastCodeAnalysis in 'func\uFastCodeAnalysis.pas',
  uCpuInstrBasicInfo in 'func\uCpuInstrBasicInfo.pas',
  uSymbols.Export in 'uSymbols.Export.pas',
  uSections.Utils in 'uSections.Utils.pas',
  uUpdateable in 'uUpdateable.pas',
  uDebugSession in 'uDebugSession.pas',
  uCore.Search in 'uCore.Search.pas',
  uRegions.SubIds in 'uRegions.SubIds.pas',
  uStrings in 'uStrings.pas',
  uEncodingAdapter in 'uEncodingAdapter.pas',
  uDumpExports in 'export\uDumpExports.pas',
  uDebugThread in 'uDebugThread.pas',
  uProblems in 'uProblems.pas',
  uFunction in 'func\uFunction.pas',
  uLoader in 'uLoader.pas',
  uLoaderTask in 'uLoaderTask.pas',
  uModule in 'uModule.pas',
  uDebugLiveCall in 'uDebugLiveCall.pas',
  uSection.Debugger in 'uSection.Debugger.pas',
  uLoader.Formats in 'uLoader.Formats.pas',
  uEvaluate.Parse in 'uEvaluate.Parse.pas',
  uEvaluate.TokenStream in 'uEvaluate.TokenStream.pas',
  uRegions.GlobalBasicBlocks in 'uRegions.GlobalBasicBlocks.pas',
  vdapi in '..\..\pub\sdk\pascal\vdapi.pas';

{$R *.res}


begin
{$IFDEF DEBUG}
  ReportMemoryLeaksOnShutdown := True;
{$ENDIF}
end.
